// Static templates for emitted Playwright projects.

export const packageJsonTemplate = (slug: string) => `{
  "name": "${slug}-tests",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "test": "playwright test",
    "test:headed": "playwright test --headed",
    "report": "playwright show-report"
  },
  "devDependencies": {
    "@playwright/test": "^1.49.0",
    "@types/node": "^22.0.0",
    "typescript": "^5.6.0",
    "dotenv": "^16.4.5"
  }
}
`;

export const playwrightConfigTemplate = (baseURL: string) => `import { defineConfig, devices } from "@playwright/test";
import fs from "node:fs";

const stateCandidate = process.env.STORAGE_STATE || ".auth/state.json";
let storageState: string | undefined;
try {
  if (fs.existsSync(stateCandidate)) {
    const parsed = JSON.parse(fs.readFileSync(stateCandidate, "utf8"));
    if ((parsed.cookies?.length ?? 0) > 0 || (parsed.origins?.length ?? 0) > 0) {
      storageState = stateCandidate;
    }
  }
} catch {}

export default defineConfig({
  testDir: "./tests",
  retries: process.env.CI ? 1 : 0,
  reporter: [["list"], ["json", { outputFile: "playwright-report.json" }]],
  use: {
    baseURL: process.env.BASE_URL || ${JSON.stringify(baseURL)},
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    storageState,
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
  ],
});
`;

export const tsconfigTemplate = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "outDir": "dist"
  },
  "include": ["tests", "page-objects", "fixtures"]
}
`;

export const envExampleTemplate = `BASE_URL=
TEST_USER=
TEST_PASS=
`;

export const readmeTemplate = (name: string, slug: string) => `# ${name} — generated tests

Generated by ai-test-gen. To run:

\`\`\`bash
npm install
npx playwright install chromium
cp .env.example .env   # set BASE_URL etc.
npm test
\`\`\`

If the suite uses authentication, drop your recorded state at \`.auth/state.json\`
(or set \`STORAGE_STATE\` to a path).

Project slug: \`${slug}\`.
`;

export const gitignoreTemplate = `node_modules
test-results
playwright-report
.auth
.env
dist
`;

export const authPlaceholder = `{
  "cookies": [],
  "origins": []
}
`;
